### ISSUE TITLE
Oshinko Web UI Templates Cannot Be oc created

### ISSUE THREAD

**Issue by sherl0cks** [radanalyticsio/oshinko-s2i#157]
if you use `oc create` to deploy oshinkoui-web or oshinko-webui-secure and via the templates at https://radanalytics.io/resources.yaml, and `oc expose svc oshinko-web` the deployment fails. The ui seems to constantly refresh, and the url redirects with the following string concatenated:

```
error?error_description=Unable+to+load+details+about+the+server.+If+the+problem+continues%2C+please+contact+your+system+administrator.&error=API_DISCOVERY
```

This means that `oc new-app` is enriching the api-objects in that List with something essential. I would like to be able to `oc apply/create` the objects so I know everything needed for deployment.

deployed to OpenShift v3.6.173.0.49

**Comment by rebeccaSimmonds19** [comment]
Cannot recreate with OpenShift 3.9 closing issue as webui is working
