### ISSUE TITLE
Oshinko Web UI Templates missing app label

### ISSUE THREAD

**Issue by sherl0cks** [radanalyticsio/oshinko-s2i#158]
`metadata.labels[app]` is need for the resulting objects to display correctly in the UI. this label is on the spring and python templates

**Comment by rebeccaSimmonds19** [comment]
@sherl0cks, is this an issue for the webui or the s2i? woudl you be able to show me the python template it is in please? thanks

**Comment by sherl0cks** [comment]
Yea its the wrong place I think. https://github.com/radanalyticsio/oshinko-webui/blob/master/tools/ui-template.yaml is the offender, but it's been a long time since I looks at this.

**Comment by rebeccaSimmonds19** [comment]
This pr should be a fix so rather than using the ui-template (which was created more for testing) we use the resources.yaml instead. Thank you for the issue! PR: https://github.com/radanalyticsio/oshinko-webui/pull/145
