### ISSUE TITLE
python3.6 image

### ISSUE THREAD

**Issue by durandom** [radanalyticsio/oshinko-s2i#207]
I wonder if there is a reason for basing the pyspark image on [python 2.7](centos/python-27-centos7:latest)

If it's as easy as changing the base image to `centos/python-36-centos7:latest` could we either bump or have a python 3.6 image ?

**Comment by mattf** [comment]
primarily timing (2 years ago not as much of the ecosystem had moved to python 3) and time (start w/ a narrow set of technologies).

there's still a lot of python 2 around, but adding python 3 should happen.

**Comment by durandom** [comment]
@elmiko what would it take to release a python3 image? _Just_ copying https://github.com/radanalyticsio/oshinko-s2i/blob/0ad7d2885fecc469b70919cacce9990b4412652f/pyspark-build/Dockerfile to a e.g. `pyspark-3-build` dir and registering that to the build pipeline?

**Comment by elmiko** [comment]
@durandom i am working on a PR to get a python3.6 s2i built for radanalytics.io

here https://github.com/elmiko/oshinko-s2i/commit/b77f279f9685b8472ce9bf669f3d43614bdf70ca is the commit i'm hacking on currently. it's a fairly simple change actually.

i have this image hosted experimentally at `docker.io/elmiko/radanalytics-pyspark:python36-latest` and a matching spark cluster image at `docker.io/elmiko/openshift-spark:python36-latest`.

i believe we will have these images landing in our repos sometime next week, i just need to finish up the testing and documentation work.

**Comment by elmiko** [comment]
@durandom as for the file you linked, you don't want to mess with the `Dockerfile` directly as this file is generated with the concreate tool.

as in my change, you want to modify the image.yaml.pyspark and related modules to make modifications on the build process. then run `make clear-context && make context` to regenerate the dockefile.

**Comment by durandom** [comment]
@elmiko awesome - I'll just hold my horses until your changes are merged. Thanks for the update

**Comment by cfchase** [comment]
I saw PR https://github.com/radanalyticsio/oshinko-s2i/pull/224 in progress.  Is this getting close?

**Comment by rebeccaSimmonds19** [comment]
PR #224 has been merged
