### ISSUE TITLE
As a Java developer, I would like to parameterize the Spark version in my pom.xml file

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-s2i#218]
While debugging issue https://github.com/radanalyticsio/radanalyticsio.github.io/issues/193  with the jgrafzahl tutorial, I realized there is an opportunity for a serious "easy mode" feature in the Java s2i.

Basically, it would be nice to know the spark version as a java developer so that i can have it passed as a parameter to my build files. This would make it much easier to include dependent packages where a version mis-match will cause the application to blow up.

It also makes maintenance much easier for applications that use the most recent releases of the radanalytics.io packages.

**Comment by elmiko** [comment]
just to clarify this a bit more, when looking at a `pom.xml` file, there are often times when the spark version is needed for various packages. [see this example](https://github.com/radanalyticsio/jgrafzahl/blob/master/pom.xml#L19)

it would be nice to have a known environment variable, or something, that could be used in a `pom.xml` file to create property variables that will inject this value. having this would allow java developers to have their build files be more dynamic and not need updating for every radanalytics spark upgrade.

**Comment by rebeccaSimmonds19** [comment]
pr #269 solves this
