### ISSUE TITLE
Investigate the possibility to add a LANG parameter/env var

### ISSUE THREAD

**Issue by rimolive** [radanalyticsio/oshinko-s2i#231]
`start.sh` will need to be flexible enough to support all languages for Spark. One proposal is label all images with the respective language and use the following env vars:

* `APP_MAIN_CLASS` is for Java/Scala when you don't have a manifest
* `APP_FILE` is for when you have more than 1 of whatever the language is looking for and start.sh can't pick
* `APP_LANG` is set in the docker file and can't be wrong, you always know what kind of app it's supposed to be this way, we could support N languages and always do the right thing no matter what

**Comment by elmiko** [comment]
this seems reasonable to me, i have a couple questions:

1. do any of the other s2i upstreams do this type of interaction? if so, is there a pattern we are following, or could follow?

2. should we perhaps name the variable `APP_LANG` just to be more explicit about the intention?

**Comment by elmiko** [comment]
another point for renaming, `LANG` is already used by the shell for determining the locale language binding

**Comment by rimolive** [comment]
1. The idea is to give the user the least parameters to configure a build with their app and let S2i workflow detect as possible what language it needs to build and detect entrypoints to that application (like we did with the MANIFEST stuff for Java/Scala apps)
2. +1, we should make clear what we mean by that param.

**Comment by elmiko** [comment]
so, is the intent that a user would specify the language through their call to `oc new-app` (for example)?

**Comment by rimolive** [comment]
Not really, it's an attempt to make S2i workflow smarter enough to know about the code it will build and use the proper base image to create the final image. But there are ambiguous situations where S2i can't detect the code correctly and then we give the users the option to explicitly tell the language used in the code.

**Comment by rebeccaSimmonds19** [comment]
PR that fixes this is #242
