### ISSUE TITLE
Custom Spark configuration is not performed when use OSHINKO_SPARK_DRIVER_CONFIG parameter when creating the app.

### ISSUE THREAD

**Issue by ohonchar** [radanalyticsio/oshinko-s2i#262]
During testing this tutorial https://radanalytics.io/howdoi/use-spark-configs, on step when try to specify OSHINKO_SPARK_DRIVER_CONFIG parameter, when creating the app, it specifying this parameter in app deployment configs, but does not performs them.

From other hand, if I use step whith manual creating cluster, useing command: "oshinko create mycluster --workerconfig=mysparkconfig --masterconfig=mysparkconfig", it deploys Spark clsters whith custom configuration without any problms.

**Comment by tmckayus** [comment]
This is working correctly, however we need to make the howdoi text more clear. The last example given there is meant to affect only the spark driver, not the spark cluster (that is, the master and worker nodes).

**Comment by rebeccaSimmonds19** [comment]
Should this be moved to https://github.com/radanalyticsio/radanalyticsio.github.io? @elmiko @tmckayus ?

**Comment by elmiko** [comment]
@rebeccaSimmonds19 @ohonchar yes, it should be an issue against the site repo

**Comment by rebeccaSimmonds19** [comment]
moved to radanalyticsio repo
