### ISSUE TITLE
failure to create cluster not detected

### ISSUE THREAD

**Issue by mattf** [radanalyticsio/oshinko-s2i#37]
sh-4.2$ echo $OSHINKO_CLUSTER_NAME
sh-4.2$ $APP_ROOT/src/oshinko-get-cluster -create
creating
[POST /clusters][500] createCluster default  &{Errors:[0xc8203241a0]}
sh-4.2$ echo $?
0

the code to detect a failure looks at $? and stdout -

https://github.com/radanalyticsio/oshinko-s2i/blob/master/common/utils/start.sh#L16

however, in the failure case $? = 0 and $output = "creating\n[POST /clusters][500] createCluster default &{Errors:[0xc8203241a0]}"

**Comment by mattf** [comment]
fyi @tmckayus

**Comment by tmckayus** [comment]
This has been fixed.  Trying to create a cluster when there is a service with a conflicting name is a good way to test:

sh-4.2$ ./oshinko-get-cluster -create oshinko-web
creating
Create cluster failed: status 409
Unable to create spark master service endpoint, err: services "oshinko-web" already exists

sh-4.2$ ./start.sh 
version 1
/etc/oshinko-spark-configs is empty, using default SPARK_CONF_DIR
Error, output from oshinko-get-cluster follows:
creating
Create cluster failed: status 409
Unable to create spark master service endpoint, err: services "oshinko-web" already exists
