### ISSUE TITLE
Ensure that workers have Python dependencies installed

### ISSUE THREAD

**Issue by willb** [radanalyticsio/oshinko-s2i#39]
MLLib in PySpark depends on NumPy, so we'll need to make sure the workers have access to it -- either via the `openshift-spark` image or via the pyspark image here (distributing NumPy to workers with the `--py-files` option to `spark-submit`).

**Comment by tmckayus** [comment]
Fixed in

https://github.com/radanalyticsio/oshinko-s2i/pull/40
