### ISSUE TITLE
Make Spark web UI, port 4040,  accessible to S2I image 

### ISSUE THREAD

**Issue by dfeddema** [radanalyticsio/oshinko-s2i#42]
Every SparkContext launches a web UI, by default on port 4040
please expose this port to S2I generated images in oshinko.

this will give the s2i template user access to
- a list of scheduler stages and tasks
- a summary of RDD sizes and memory usage (useful for tuning and debugging)
- environment settings
- view of running executors and state of each thread

**Comment by mattf** [comment]
@dfeddema is this still an issue now that we are using spark 2.1 and have reverseProxy enabled?

**Comment by rebeccaSimmonds19** [comment]
The latest version of Spark and the reverse proxy fixes this:

"Enable running Spark Master as reverse proxy for worker and application UIs. In this mode, Spark master will reverse proxy the worker and application UIs to enable access without requiring direct access to their hosts."
