### ISSUE TITLE
sudo usage should be removed from makefile

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-s2i#5]
it seems that the makefiles include sudo usage explicitly for the purpose of running docker. i think we should not be embedding sudo usage into the makefile as it can be an unwelcome surprise.

we should move the sudo usage outside of the makefile, with some documentation about the possible need to run as root, as well as links to the docker documentation about configuring non-root usage.

example docker config https://docs.docker.com/engine/installation/linux/rhel/#/create-a-docker-group

**Comment by tmckayus** [comment]
There currently are no sudo commands in make files
