### ISSUE TITLE
delete cluster operations always return 204

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-s2i#51]
When making a DELETE against an endpoint the server is always responding with a 204, it should only respond that way when the call is successful. In the case of non-existent clusters the server should return a 404.

logs of current behavior
```
$ http 172.17.0.4:8081/clusters
HTTP/1.1 200 OK
Content-Length: 16
Content-Type: application/json
Date: Fri, 04 Nov 2016 19:37:11 GMT
Vary: Origin

{
    "clusters": []
}

[mike@shell] ~
$ http DELETE 172.17.0.4:8081/clusters/foo
HTTP/1.1 204 No Content
Content-Type: application/json
Date: Fri, 04 Nov 2016 19:37:20 GMT
Vary: Origin
```

**Comment by tmckayus** [comment]
This should really be on the oshinko-rest repo, duplicating and closing
