### ISSUE TITLE
buildconfigs should use "forcePull: true"

### ISSUE THREAD

**Issue by tmckayus** [radanalyticsio/oshinko-s2i#53]
Setting forcePull set to true will cause the latest image to be retrieved from the source. In the case the buildconfigs in the oshinko templates, the source is radanalyticsio/radanalytics-pyspark.  Without the forcePull the cluster nodes will use a local image, which may be stale.

This is analogous to the imagePullPolicy settings on containers

**Comment by elmiko** [comment]
fixed by #57
