### ISSUE TITLE
No assemble scripts in the pyspark s2i directoy

### ISSUE THREAD

**Issue by thesteve0** [radanalyticsio/oshinko-s2i#55]
All S2I images are supposed to have an assemble/build script so they can actually do things like pull down requirements. I do not see that in the pyspark s2i.

**Comment by thesteve0** [comment]
Is that because you are using the assemble script from the base docker s2i image?

**Comment by tmckayus** [comment]
Yes, the assemble script is inherited from the base image in this case, no mods were necessary
