### ISSUE TITLE
suggestion: add a container based build solution

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-s2i#6]
currently, building the oshinko-get-cluster application can cumbersome when building out of the GOPATH. it would be really nice to have a container based builder which would simplify the process of making the get-cluster.

**Comment by tmckayus** [comment]
This is partially addressed by https://github.com/radanalyticsio/oshinko-s2i/pull/36/files

In that case, oshinko-get-cluster will be built in the image. Do we need to do more?

**Comment by rebeccaSimmonds19** [comment]
There is no oshinko-get-cluster anymore
