### ISSUE TITLE
Add some examples for pyspark and java s2i builders for users to try s2i

### ISSUE THREAD

**Issue by tmckayus** [radanalyticsio/oshinko-s2i#77]
We need to set up some examples that users can just push through s2i as a tutorial to see how it works.

**Comment by mattf** [comment]
i can move https://github.com/mattf/py-smoke into radanalytcsio as a basic python s2i example

**Comment by elmiko** [comment]
could we point people to the tutorials on radanalytics.io for this?

**Comment by rebeccaSimmonds19** [comment]
https://radanalytics.io/tutorials

This issue is no longer needed, the solutions group are covering this
