### ISSUE TITLE
restarting a pyspark s2i application causes the spark cluster to be redeployed

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-s2i#81]
i noticed this while playing around with an application, that when i delete the pod for an s2i based application that when the new pod comes up it will deploy the spark cluster again without deleting the old cluster. not sure the best way to handle this, we need to either delete the old cluster or retain its information for the new app.

**Comment by mattf** [comment]
cc @tmckayus 

this might be the result of my suggestion to push the name generation down.

https://github.com/radanalyticsio/oshinko-s2i/blob/master/common/utils/start.sh#L43

if the name is chosen at the template/dc level the redeployed app should simply reattach.

**Comment by mattf** [comment]
see https://github.com/radanalyticsio/oshinko-s2i/pull/32

**Comment by tmckayus** [comment]
Currently ephemeral clusters are deleted by the start.sh script when the app is "finished".  For a streaming app with an ephemeral cluster, the app will never actually finish.  With a batch job it will, but if you delete the pod before that point the cluster will be left. This is definitely an oversight.

We do not currently have anything "watching" clusters/apps and looking for clusters that should be deleted.  However, there are other reasons we want to have a tighter association between apps and clusters through labeling/annotations and fixing this may dovetail with those efforts.

**Comment by mattf** [comment]
would it fit into the use case to specify a cluster name for a streaming app and thus re-use the cluster across app rollouts?

**Comment by elmiko** [comment]
i was able to work with the `OSHINKO_CLUSTER_NAME` variable to avoid creating new clusters. it made my `oc new-app` command a little longer, but really improved usability.

**Comment by tmckayus** [comment]
Note, this is a PR to address some of the issues raised above.

https://github.com/radanalyticsio/oshinko-s2i/pull/98

This will handle deletion of an ephemeral cluster on driver pod termination, if it has not already been cleaned up.

Whether and how to re-use cluster names of redeployed pods for the same application is another question that ties into app/cluster grouping.

**Comment by tmckayus** [comment]
This should not be an issue with current ephemeral cluster handling.
