### ISSUE TITLE
Java S2I Spark is not running. Problems with UID and SCC in CDK.

### ISSUE THREAD

**Issue by rimolive** [radanalyticsio/oshinko-s2i#94]
While running a Java app with S2I Spark image I'm getting the error in the link below:

https://gist.github.com/rimolive/a01638ce29db19887f322a32154aae0d

I'm using the parameters in this link: https://gist.github.com/rimolive/ebae5598b407fc6193870286892962bf

After some troubleshooting steps, the following is suspected:

* $APP_ROOT/etc/generate_container_user is not set as executable
* /opt/app-root/etc/passwd file is missing
* oc rsh <pod_name> -- id is returning user ID 1001
* The pod is set to user anyuid SCC

As Matt said:
~~~
something about the CDK is letting your pod run as uid 1001 and thus skip the nss setup (https://github.com/radanalyticsio/oshinko-s2i/blob/master/java/generate_container_user#L5). we should be able to fix this by setting up nss whenever the uid isn't in passwd, instead of assuming 0 and 1001 are safe
~~~

**Comment by tmckayus** [comment]
Not sure the executable bit matters on generate_container_user, as we "source" it in start.sh

Working on a fix to generate_container_user to check for presence of UID in /etc/passwd instead of comparing to 0 or 1001

**Comment by tmckayus** [comment]
@rimolive, I believe this is fixed now, would you agree?

**Comment by rimolive** [comment]
Correct. I tested the last image version and it is working now.

**Comment by tmckayus** [comment]
Great!
